# Server configuration
server:
  listen_address: "0.0.0.0"       # Address to bind the server (default: 0.0.0.0)
  port: "8443"                    # Port to listen on (default: 8443)
  enable_tls: true                # Enable TLS (default: true)
  tls:
    cert_file: "certs/server-cert.pem" # Server certificate file
    key_file: "certs/server-key.pem"   # Server private key file
    ca_file: "certs/ca-cert.pem"       # CA certificate file
    min_version: "TLSv1.3"             # Minimum TLS version (options: TLSv1.1, TLSv1.2, TLSv1.3)

# etcd configuration
etcd:
  endpoints:
    - "localhost:2379"            # etcd server endpoint (default: localhost:2379)
  enable_tls: true                # Enable TLS for etcd (default: true)
  tls:
    cert_file: "certs/client-cert.pem" # Client certificate file
    key_file: "certs/client-key.pem"   # Client private key file

# Encryption settings
encryption:
  key: "${ENCRYPTION_KEY}"        # Encryption key (32 bytes, set via environment variable)

# Two-factor authentication settings
two_factor:
  enabled: true                   # Enable 2FA (default: true)
  secret: "${TWO_FACTOR_SECRET}"  # 2FA secret (set via environment variable)

# Logging configuration
logging:
  access_file: "logs/access.log"  # Access log file path (default: logs/access.log)
  level: "debug"                  # Log level (options: debug, info, warn, error)
